version: 1

jobs:
  build:

    docker:
      - image: mrpossoms/ubuntu-dev-base:latest
        environment:

    steps:
      - checkout

      - run:
          name: Fetch Dependencies
          command: gitman install

      - run:
          name: Run tests
          command: make -C tests test

