name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Gitman
      run: pip3 install gitman

    - name: Install Dependencies
      run: gitman install

    - uses: actions/checkout@v2
    - name: run tests
      run: make -C ./tests test
